# coding: utf-8

"""
    Genedata

    API for interacting with gene records  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_gene(self):
        """Test case for create_gene

        """
        pass

    def test_destroy_gene(self):
        """Test case for destroy_gene

        """
        pass

    def test_list_genes(self):
        """Test case for list_genes

        """
        pass

    def test_retrieve_gene(self):
        """Test case for retrieve_gene

        """
        pass

    def test_update_gene(self):
        """Test case for update_gene

        """
        pass


if __name__ == '__main__':
    unittest.main()
