# Generated by Django 4.2.4 on 2023-09-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
