# coding: utf-8

# flake8: noqa

"""
    Genedata

    API for interacting with gene records  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.apigeneid_ec import ApigeneidEc
from swagger_client.models.apigeneid_sequencing import ApigeneidSequencing
from swagger_client.models.body import Body
from swagger_client.models.body1 import Body1
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
