# Generated by Django 4.2.4 on 2023-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0007_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://icon-library.com/images/default-profile-icon/default-profile-icon-16.jpg'),
        ),
    ]
