# Generated by Django 4.2.4 on 2023-09-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0008_alter_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
