# Generated by Django 4.2.1 on 2023-05-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=256)),
                ('entity', models.CharField(max_length=256)),
                ('start', models.IntegerField(blank=True)),
                ('stop', models.IntegerField(blank=True)),
                ('sense', models.CharField(max_length=1)),
                ('start_codon', models.CharField(default='M', max_length=1)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.ec')),
            ],
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencing_factory', models.CharField(max_length=256)),
                ('factory_location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('product', models.CharField(max_length=256)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genedata.gene')),
            ],
        ),
        migrations.CreateModel(
            name='GeneAttributeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.attribute')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.gene')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='sequencing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.sequencing'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='gene',
            field=models.ManyToManyField(through='genedata.GeneAttributeLink', to='genedata.gene'),
        ),
    ]
