# Generated by Django 4.2.1 on 2023-07-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(db_index=True, max_length=256)),
                ('amino_acid_sequence', models.CharField(max_length=40000)),
            ],
        ),
        migrations.RemoveField(
            model_name='domainannotation',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='domainannotation',
            name='protein',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='DomainAnnotation',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
    ]
