# Generated by Django 4.2.1 on 2023-07-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_detail_remove_domainannotation_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='amino_acid_sequence',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='detail',
            name='protein_id',
            field=models.CharField(db_index=True, max_length=256, primary_key=True, serialize=False),
        ),
    ]
