# Generated by Django 4.2.4 on 2023-09-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_updated_at_chat_unique_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_users',
        ),
    ]
