# Generated by Django 4.2.1 on 2023-07-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainannotation',
            old_name='domain',
            new_name='pfam_id',
        ),
    ]
