# Generated by Django 4.2.1 on 2023-07-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfam', '0002_rename_domain_domainannotation_pfam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='pfam_id',
            new_name='domain_id',
        ),
    ]
