# Generated by Django 4.2.1 on 2023-07-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfam', '0003_rename_pfam_id_domain_domain_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainannotation',
            old_name='pfam_id',
            new_name='pfam',
        ),
    ]
