# Generated by Django 4.2.4 on 2023-09-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_remove_statusupdate_media_statusupdate_medias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdate',
            old_name='medias',
            new_name='media',
        ),
    ]
