# Generated by Django 4.2.4 on 2023-09-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_statusupdate_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdate',
            old_name='media',
            new_name='medias',
        ),
    ]
