# Generated by Django 4.2.4 on 2023-09-02 00:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_rename_media_statusupdate_medias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='medias',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='medias'),
        ),
    ]
