# Generated by Django 4.2.1 on 2023-07-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0003_rename_amino_acid_sequence_detail_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('pfam_id', models.CharField(db_index=True, max_length=256, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DomainAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(blank=True)),
                ('stop', models.IntegerField(blank=True)),
                ('taxa_id', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=256)),
                ('clade', models.CharField(default='E', max_length=256)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('length', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='pfam.domain')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein', to='protein.detail')),
            ],
        ),
    ]
