# Generated by Django 4.2.1 on 2023-07-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfam', '0005_alter_domainannotation_pfam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainannotation',
            old_name='pfam',
            new_name='pfam_id',
        ),
    ]
