# Generated by Django 4.2.1 on 2023-07-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfam', '0006_rename_pfam_domainannotation_pfam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainannotation',
            old_name='pfam_id',
            new_name='pfam',
        ),
    ]
