# Generated by Django 4.2.4 on 2023-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0004_user_avatar_url_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://icon-library.com/images/default-profile-icon/default-profile-icon-16.jpg'),
        ),
    ]
